stochastic_dim: 256
device: "cuda:0"
encoder_params:
  fc1_hidden: 1024
  fc2_hidden: 512
  dropout_p: 0.3
  resnet_type: "resnet50"
decoder_params:
  fc1_hidden: 512
  fc2_hidden: 1024
  fc3_hidden: 2048
  dropout_p: 0.3
